server:
    port: 9090

spring:
    application:
        name: api-gateway

    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
                    issuer-uri: http://localhost:8080/realms/myrealm
            client:
                registration:
                    keycloak:
                        client-id: myclient
                        authorization-grant-type: authorization_code
                        scope: openid
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/realms/myrealm
                        user-name-attribute: preferred_username

    cloud:
        gateway:
            mvc:
                routes:
                    -   id: user-service
                        uri: http://localhost:8082
                        predicates:
                            - Path=/user-service/**
                        filters:
                            - RewritePath=/user-service/(?<remaining>.*), /${remaining}
                    -   id: admin-service
                        uri: http://localhost:8085
                        predicates:
                            - Path=/admin-service/**
                        filters:
                            - RewritePath=/admin-service/(?<remaining>.*), /${remaining}
                    -   id: teacher-service
                        uri: http://localhost:8084
                        predicates:
                            - Path=/teacher-service/**
                        filters:
                            - RewritePath=/teacher-service/(?<remaining>.*), /${remaining}
                    -   id: student-service
                        uri: http://localhost:8083
                        predicates:
                            - Path=/student-service/**
                        filters:
                            - RewritePath=/student-service/(?<remaining>.*), /${remaining}
                    -   id: course-service
                        uri: http://localhost:8086
                        predicates:
                            - Path=/course-service/**
                        filters:
                            - RewritePath=/course-service/(?<remaining>.*), /${remaining}
                    -   id: file-service
                        uri: http://localhost:8087
                        predicates:
                            - Path=/file-service/**
                        filters:
                            - RewritePath=/file-service/(?<remaining>.*), /${remaining}
                    -   id: hw-service
                        uri: http://localhost:8088
                        predicates:
                            - Path=/hw-service/**
                        filters:
                            - RewritePath=/hw-service/(?<remaining>.*), /${remaining}
                    -   id: response-service
                        uri: http://localhost:8089
                        predicates:
                            - Path=/response-service/**
                        filters:
                            - RewritePath=/response-service/(?<remaining>.*), /${remaining}
                    -   id: course-access-service
                        uri: http://localhost:8090
                        predicates:
                            - Path=/course-access-service/**
                        filters:
                            - RewritePath=/course-access-service/(?<remaining>.*), /${remaining}

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/