server:
    port: 9090

spring:
    application:
        name: api-gateway

    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
                    issuer-uri: http://localhost:8080/realms/myrealm
            client:
                registration:
                    keycloak:
                        client-id: myclient
                        authorization-grant-type: authorization_code
                        scope: openid
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/realms/myrealm
                        user-name-attribute: preferred_username

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/