server:
    port: 8086

spring:
    application:
        name: course-service
    data:
        neo4j:
            database: neo4j
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: radya2004

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/