server:
    port: 8083

spring:
    application:
        name: student-service
    datasource:
        url: jdbc:mysql://localhost:3306/course_project_students?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka
