server:
    port: 8086

spring:
    application:
        name: course-access-service
    datasource:
        url: jdbc:mysql://localhost:3306/course_access_service
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/