server:
    port: 8093

grpc:
    server:
        port: 6565

spring:
    application:
        name: task-file-requirements-service
    datasource:
        url: jdbc:mysql://localhost:3306/task_file_requirements?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka
