server:
    port: 8086

spring:
    application:
        name: course-service
    data:
        neo4j:
            database: neo4j
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: radya2004
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    cache:
        redis:
            time-to-live: 3600000

management:
    endpoints:
        web:
            exposure:
                include: "metrics, prometheus"
        health:
            show-details: always
    metrics:
        export:
            prometheus:
                enabled: true
    tracing:
        enabled: true
        sampling:
            probability: 1.0
    otlp:
        tracing:
            endpoint: http://localhost:4318/v1/traces

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/