server:
    port: 8089

grpc:
    server:
        port: 6572
    client:
        progress-grpc-client:
            address: static://localhost:6571
            negotiation-type: plaintext
        course-rights-grpc-client:
            address: static://localhost:6566
            negotiation-type: plaintext

spring:
    application:
        name: hw-response-service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    data:
        mongodb:
            uri: mongodb://localhost:27017/course_project_hw_responses

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/
