server:
    port: 8089

spring:
    application:
        name: hw-response-service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    data:
        mongodb:
            uri: mongodb://localhost:27017/course_project_hw_responses
    kafka:
        bootstrap-servers: localhost:9092

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/
