server:
    port: 8098

spring:
    application:
        name: hw-response-service-saga
    kafka:
        bootstrap-servers: localhost:9092

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/