server:
    port: 8096

spring:
    application:
        name: hw-service-saga
    kafka:
        bootstrap-servers: localhost:9092
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 30MB

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/