server:
    port: 8082

spring:
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://localhost:3306/course_project_users?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka