server:
    port: 8092

grpc:
    server:
        port: 6571

spring:
    application:
        name: progress-service
    datasource:
        url: jdbc:mysql://localhost:3306/progress
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/